# Generated by Django 5.2.2 on 2025-06-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_FBV', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cosa',
        ),
    ]
